"""initial_schema

Revision ID: cfa545c82657
Revises: 
Create Date: 2026-09-25 11:41:59.658480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa545c82657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('cohort_year', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('academic_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('Medu', sa.Integer(), nullable=False),
    sa.Column('Fedu', sa.Integer(), nullable=False),
    sa.Column('traveltime', sa.Integer(), nullable=False),
    sa.Column('studytime', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('famrel', sa.Integer(), nullable=False),
    sa.Column('freetime', sa.Integer(), nullable=False),
    sa.Column('goout', sa.Integer(), nullable=False),
    sa.Column('Dalc', sa.Integer(), nullable=False),
    sa.Column('Walc', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('absences', sa.Integer(), nullable=False),
    sa.Column('G1', sa.Float(), nullable=False),
    sa.Column('G2', sa.Float(), nullable=False),
    sa.Column('school', sa.String(length=10), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('address', sa.String(length=5), nullable=False),
    sa.Column('famsize', sa.String(length=10), nullable=False),
    sa.Column('Pstatus', sa.String(length=5), nullable=False),
    sa.Column('schoolsup', sa.String(length=5), nullable=False),
    sa.Column('famsup', sa.String(length=5), nullable=False),
    sa.Column('paid', sa.String(length=5), nullable=False),
    sa.Column('activities', sa.String(length=5), nullable=False),
    sa.Column('nursery', sa.String(length=5), nullable=False),
    sa.Column('higher', sa.String(length=5), nullable=False),
    sa.Column('internet', sa.String(length=5), nullable=False),
    sa.Column('romantic', sa.String(length=5), nullable=False),
    sa.Column('Mjob', sa.String(length=20), nullable=False),
    sa.Column('Fjob', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('guardian', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_records_id'), 'academic_records', ['id'], unique=False)
    op.create_index(op.f('ix_academic_records_student_id'), 'academic_records', ['student_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_record_id', sa.Integer(), nullable=True),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('at_risk_binary', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_record_id'], ['academic_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_academic_record_id'), 'predictions', ['academic_record_id'], unique=False)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_student_id'), 'predictions', ['student_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('raw_value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_id'), 'explanations', ['id'], unique=False)
    op.create_index(op.f('ix_explanations_prediction_id'), 'explanations', ['prediction_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('trigger_condition', sa.String(length=100), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_prediction_id'), 'recommendations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_prediction_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_explanations_prediction_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_id'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_predictions_student_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_academic_record_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_academic_records_student_id'), table_name='academic_records')
    op.drop_index(op.f('ix_academic_records_id'), table_name='academic_records')
    op.drop_table('academic_records')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
